# Generated by Django 4.2.4 on 2023-08-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_produto', models.TextField()),
                ('nome_produto', models.TextField()),
                ('qtidade_produto', models.IntegerField()),
                ('obs_produto', models.TextField()),
            ],
        ),
    ]
