# Generated by Django 4.2.4 on 2023-08-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='qtidade_produto',
            field=models.TextField(),
        ),
    ]
